n = int(input('Digite um numero: '))
print('Tabuada do numero digitado a seguir\n:')
print(n * 0)
print(n * 1)
print(n * 2)
print(n * 3)
print(n * 4)
print(n * 5)
print(n * 6)
print(n * 7)
print(n * 8)
print(n * 9)
print(n * 10)